### ISSUE TITLE
Please correct the default VPC architecture diagram

### ISSUE THREAD

**Issue by bilalbox** [mulesoft/docs-runtime-manager#150]
Please update the first diagram in [this document](https://docs.mulesoft.com/runtime-manager/vpc-architecture-concept), the diagram directly below the verbiage "**The graphic below shows a default Anypoint VPC architecture:**"

The bottom path that depicts connecting to mule-worker-internal-<app-name>.cloudhub.io on ports 8091 and 8092 is incorrect...**it should show connections on ports 8081 and 8082** instead...

Remember that ports **8091 and 8092** are only used in the case where **dedicated load-balancer** is used.

Updating this diagram will help lots of folks better understand what firewall rules are required to allow minimal connectivity in their VPCs and minimize confusion.

Thanks!

**Comment by hannanelson** [comment]
Thanks - I've created an issue for my backlog :)

**Comment by hannanelson** [comment]
This is fixed: https://docs.mulesoft.com/runtime-manager/vpc-architecture-concept
