### ISSUE TITLE
Missing the deploy endpoint in V2 API

### ISSUE THREAD

**Issue by yyamano** [mulesoft/docs-runtime-manager#336]
CloudHub API v2 doesn't have the following endpoint. Coud you update the doc?

https://github.com/mulesoft/docs-runtime-manager/blob/latest/modules/ROOT/pages/deploy-application.adoc

> POST https://anypoint.mulesoft.com/cloudhub/api/applications/hello/deploy

**Comment by hannanelson** [comment]
Thanks @yyamano - We are currently in the process of deprecating the CH API details in the docs in favor of the API on Exchange.
