### ISSUE TITLE
Error public certificate chain is invalid (the Nth certificate must be signed by Nth+1)

### ISSUE THREAD

**Issue by sbhakta99** [mulesoft/docs-runtime-manager#416]
I am getting the following message when attempting to Replace a Certificate on an Existing Load Balancer

public certificate chain is invalid (the Nth certificate must be signed by Nth+1)

I am following this doc.
https://docs.mulesoft.com/runtime-manager/lb-cert-upload#replace-a-certificate-on-an-existing-load-balancer

When only 1 cert (The Primary Certificate) is included in the public.pem it works but when we add multiple chain such as both The Primary Certificate & The Intermediate Certificate it throw this error.  Please attempt to duplicate, it worked for us last time.

The Primary Certificate
-----BEGIN CERTIFICATE-----
(Your Primary SSL certificate: your_domain_name.crt)
-----END CERTIFICATE-----

The Intermediate Certificate
-----BEGIN CERTIFICATE-----
(Your Intermediate certificate: DigiCertCA.crt)
-----END CERTIFICATE-----
![Screen Shot 2020-11-09 at 8 56 55 AM](https://user-images.githubusercontent.com/6462691/98565470-e479d700-226a-11eb-8cc8-41a6109ba182.png)

**Comment by danieldiaz-mule** [comment]
This is a non-issue, the chain was being built using the old ICA certificate:
https://knowledge.digicert.com/alerts/DigiCert-ICA-Update.html
