### ISSUE TITLE
"System available processing power" metric is unclear

### ISSUE THREAD

**Issue by phubbard-mulesoft** [mulesoft/docs-runtime-manager#502]
Under 'Overview' we have the following text:

```
CPU
This metric is not available on Windows.

The total CPU usage of the server, as a percentage:

CPU usage

System available processing power

System load average
```

The field "System available processing power" has no metric. Additionally, the current Anypoint Platform interface calls this field "Available Processors". Please clearly define what this field is measuring.

**Comment by hannanelson** [comment]
@phubbard-mulesoft - can you provide the URL of the topic you're referring to?

**Comment by phubbard-mulesoft** [comment]
Sorry, here you go: https://docs.mulesoft.com/runtime-manager/monitoring-dashboards#server-monitoring-dashboard

**Comment by luanamulesoft** [comment]
The documentation has been updated with a definition of each of the CPU Usage metrics displayed in the graphic.
