### ISSUE TITLE
Deployment Strategies lacks JDK associated with Mule Runtime 4.x

### ISSUE THREAD

**Issue by mak-dt** [mulesoft/docs-runtime-manager#573]
As per the JDK Versions of Mule Runtime [Deployment Strategies](https://github.com/mulesoft/docs-runtime-manager/blob/bfb714a8f11e16f01184d37f03b61bfc02071614/modules/ROOT/pages/deployment-strategies.adoc)
```
JDK versions

The version of JDK that CloudHub implements for all apps built with Mule runtime 3.5.1 or later is JDK 1.7. Mule runtime 3.7.0 also supports JDK 1.8. Apps built with runtime 3.5.0 or earlier are deployed with JDK 1.6.
```

However, under the Additional Information section of the Support Article [Java 11 Support in CloudHub Runtimes](https://help.mulesoft.com/s/article/Java-11-Support-in-CloudHub-Runtimes)

`Mule Runtime 4.x does support JDK 11, however as of the publishing of this article, all CloudHub and Anypoint Platform Services are deployed on JDK8.`

This causes confusion on the actual JDK/JRE for Mule Runtimes 4.x and is further complicated by the Article [Mule Runtime support for Java 11 FAQ](https://help.mulesoft.com/s/article/Mule-Runtime-support-for-Java-11-FAQ) into consideration.

**Comment by luanamulesoft** [comment]
Hi! Thank you for reporting this issue. We are currently addressing it with our devs, and will let you know once this is solved.

**Comment by luanamulesoft** [comment]
We have addressed the reported issue and updated our documentation accordingly.
