### ISSUE TITLE
VPC Discovery Form does not resolve

### ISSUE THREAD

**Issue by comikem** [mulesoft/docs-runtime-manager#618]
The links to the VPC Discovery form 9.5 result in a 404 for customers and internal users.

[https://docs.mulesoft.com/runtime-manager/to-request-vpc-connectivity](Docs page)
[https://docs.mulesoft.com/downloads/runtime-manager/VPC-form-v9.5-template.xlsx] (Missing file)

**Comment by luanamulesoft** [comment]
Hello. Thank you for reporting this. The link was fixed.
